#!/bin/sh

# Shell script for starting/stopping the LabStreamingLayer  python script

PIDFILE="/run/LabStreamingLayer.pid"
DAEMON="/opt/cava/LabStreamingLayer.py"
ARGS="-d"
LOG="/opt/cava-log/LabStreamingLayer.log"

#export DISPLAY="localhost:0.0"
#export DISPLAY="localhost:0.0"

start() {
    # Check if we are already started, do not start a second daemon
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        echo "LabStreamingLayer already started with process ID $PID, not starting a new instance" >> $LOG
        exit
    fi

    # Exec process with the keyboard listener
    #exec python3 $DAEMON #$ARGS
    exec python3 $DAEMON

    # Store the process ID and lock file for later use
    #PID="$!" 
    #echo $PID > $PIDFILE
    #echo "LabStreamingLayer started with PID $PID"
}

stop() {
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        echo "Killing LabStreamingLayer script with PID $PID" >> $LOG
        kill -15 $PID
	    sleep 1
        # PID file is automatically removed by systemd
        if [ -f $PIDFILE ]; then
            rm $PIDFILE
        fi
    else
        echo "PID file not found" >> $LOG
    fi


}


case $1 in
    start|stop) "$1" ;;
esac
